// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module workload_hotspot_stencil_core (
        ap_clk,
        ap_rst,
        temp_top,
        temp_left,
        temp_right,
        temp_bottom,
        temp_center,
        power_center,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [31:0] temp_top;
input  [31:0] temp_left;
input  [31:0] temp_right;
input  [31:0] temp_bottom;
input  [31:0] temp_center;
input  [31:0] power_center;
output  [31:0] ap_return;

reg   [31:0] power_center_read_reg_125;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
wire    ap_block_state31_pp0_stage0_iter30;
wire    ap_block_state32_pp0_stage0_iter31;
wire    ap_block_state33_pp0_stage0_iter32;
wire    ap_block_state34_pp0_stage0_iter33;
wire    ap_block_state35_pp0_stage0_iter34;
wire    ap_block_state36_pp0_stage0_iter35;
wire    ap_block_state37_pp0_stage0_iter36;
wire    ap_block_state38_pp0_stage0_iter37;
wire    ap_block_state39_pp0_stage0_iter38;
wire    ap_block_state40_pp0_stage0_iter39;
wire    ap_block_state41_pp0_stage0_iter40;
wire    ap_block_state42_pp0_stage0_iter41;
wire    ap_block_state43_pp0_stage0_iter42;
wire    ap_block_state44_pp0_stage0_iter43;
wire    ap_block_state45_pp0_stage0_iter44;
wire    ap_block_state46_pp0_stage0_iter45;
wire    ap_block_state47_pp0_stage0_iter46;
wire    ap_block_state48_pp0_stage0_iter47;
wire    ap_block_state49_pp0_stage0_iter48;
wire    ap_block_state50_pp0_stage0_iter49;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] power_center_read_reg_125_pp0_iter1_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter2_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter3_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter4_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter5_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter6_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter7_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter8_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter9_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter10_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter11_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter12_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter13_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter14_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter15_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter16_reg;
reg   [31:0] power_center_read_reg_125_pp0_iter17_reg;
reg   [31:0] temp_center_read_reg_130;
reg   [31:0] temp_center_read_reg_130_pp0_iter1_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter2_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter3_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter4_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter5_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter6_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter7_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter8_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter9_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter10_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter11_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter12_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter13_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter14_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter15_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter16_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter17_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter18_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter19_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter20_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter21_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter22_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter23_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter24_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter25_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter26_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter27_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter28_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter29_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter30_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter31_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter32_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter33_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter34_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter35_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter36_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter37_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter38_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter39_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter40_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter41_reg;
reg   [31:0] temp_center_read_reg_130_pp0_iter42_reg;
wire   [31:0] grp_fu_58_p2;
reg   [31:0] tmp_reg_158;
wire   [31:0] grp_fu_64_p2;
reg   [31:0] add1_reg_164;
wire   [31:0] grp_fu_70_p2;
reg   [31:0] add2_reg_169;
wire   [31:0] grp_fu_76_p2;
reg   [31:0] tmp0_reg_174;
wire   [31:0] grp_fu_80_p2;
reg   [31:0] tmp1_reg_179;
reg   [31:0] tmp1_reg_179_pp0_iter14_reg;
reg   [31:0] tmp1_reg_179_pp0_iter15_reg;
reg   [31:0] tmp1_reg_179_pp0_iter16_reg;
reg   [31:0] tmp1_reg_179_pp0_iter17_reg;
reg   [31:0] tmp1_reg_179_pp0_iter18_reg;
reg   [31:0] tmp1_reg_179_pp0_iter19_reg;
reg   [31:0] tmp1_reg_179_pp0_iter20_reg;
wire   [31:0] grp_fu_105_p2;
reg   [31:0] mul_reg_184;
wire   [31:0] grp_fu_84_p2;
reg   [31:0] power_center_assign_reg_189;
wire   [31:0] grp_fu_110_p2;
reg   [31:0] mul6_reg_194;
wire   [31:0] grp_fu_88_p2;
reg   [31:0] tmp2_reg_199;
wire   [31:0] grp_fu_93_p2;
reg   [31:0] power_center_assign_1_reg_204;
wire   [31:0] grp_fu_115_p2;
reg   [31:0] mul8_reg_209;
wire   [31:0] grp_fu_97_p2;
reg   [31:0] power_center_assign_2_reg_214;
wire   [31:0] grp_fu_120_p2;
reg   [31:0] mul1_reg_219;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_101_p2;
reg   [31:0] temp_top_int_reg;
reg   [31:0] temp_left_int_reg;
reg   [31:0] temp_right_int_reg;
reg   [31:0] temp_bottom_int_reg;
reg   [31:0] temp_center_int_reg;
reg   [31:0] power_center_int_reg;

workload_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_center_int_reg),
    .din1(temp_center_int_reg),
    .ce(1'b1),
    .dout(grp_fu_58_p2)
);

workload_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_top_int_reg),
    .din1(temp_bottom_int_reg),
    .ce(1'b1),
    .dout(grp_fu_64_p2)
);

workload_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_left_int_reg),
    .din1(temp_right_int_reg),
    .ce(1'b1),
    .dout(grp_fu_70_p2)
);

workload_fsub_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_7_full_dsp_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add1_reg_164),
    .din1(tmp_reg_158),
    .ce(1'b1),
    .dout(grp_fu_76_p2)
);

workload_fsub_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_7_full_dsp_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add2_reg_169),
    .din1(tmp_reg_158),
    .ce(1'b1),
    .dout(grp_fu_80_p2)
);

workload_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_reg_184),
    .din1(power_center_read_reg_125_pp0_iter17_reg),
    .ce(1'b1),
    .dout(grp_fu_84_p2)
);

workload_fsub_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_7_full_dsp_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1117782016),
    .din1(temp_center_read_reg_130_pp0_iter20_reg),
    .ce(1'b1),
    .dout(grp_fu_88_p2)
);

workload_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(power_center_assign_reg_189),
    .din1(mul6_reg_194),
    .ce(1'b1),
    .dout(grp_fu_93_p2)
);

workload_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(power_center_assign_1_reg_204),
    .din1(mul8_reg_209),
    .ce(1'b1),
    .dout(grp_fu_97_p2)
);

workload_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul1_reg_219),
    .din1(temp_center_read_reg_130_pp0_iter42_reg),
    .ce(1'b1),
    .dout(grp_fu_101_p2)
);

workload_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp0_reg_174),
    .din1(32'd1036831949),
    .ce(1'b1),
    .dout(grp_fu_105_p2)
);

workload_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp1_reg_179_pp0_iter20_reg),
    .din1(32'd1036831949),
    .ce(1'b1),
    .dout(grp_fu_110_p2)
);

workload_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp2_reg_199),
    .din1(32'd961334477),
    .ce(1'b1),
    .dout(grp_fu_115_p2)
);

workload_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(power_center_assign_2_reg_214),
    .din1(32'd1024184164),
    .ce(1'b1),
    .dout(grp_fu_120_p2)
);

always @ (posedge ap_clk) begin
    power_center_int_reg <= power_center;
end

always @ (posedge ap_clk) begin
    temp_bottom_int_reg <= temp_bottom;
end

always @ (posedge ap_clk) begin
    temp_center_int_reg <= temp_center;
end

always @ (posedge ap_clk) begin
    temp_left_int_reg <= temp_left;
end

always @ (posedge ap_clk) begin
    temp_right_int_reg <= temp_right;
end

always @ (posedge ap_clk) begin
    temp_top_int_reg <= temp_top;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add1_reg_164 <= grp_fu_64_p2;
        add2_reg_169 <= grp_fu_70_p2;
        mul1_reg_219 <= grp_fu_120_p2;
        mul6_reg_194 <= grp_fu_110_p2;
        mul8_reg_209 <= grp_fu_115_p2;
        mul_reg_184 <= grp_fu_105_p2;
        power_center_assign_1_reg_204 <= grp_fu_93_p2;
        power_center_assign_2_reg_214 <= grp_fu_97_p2;
        power_center_assign_reg_189 <= grp_fu_84_p2;
        power_center_read_reg_125 <= power_center_int_reg;
        power_center_read_reg_125_pp0_iter10_reg <= power_center_read_reg_125_pp0_iter9_reg;
        power_center_read_reg_125_pp0_iter11_reg <= power_center_read_reg_125_pp0_iter10_reg;
        power_center_read_reg_125_pp0_iter12_reg <= power_center_read_reg_125_pp0_iter11_reg;
        power_center_read_reg_125_pp0_iter13_reg <= power_center_read_reg_125_pp0_iter12_reg;
        power_center_read_reg_125_pp0_iter14_reg <= power_center_read_reg_125_pp0_iter13_reg;
        power_center_read_reg_125_pp0_iter15_reg <= power_center_read_reg_125_pp0_iter14_reg;
        power_center_read_reg_125_pp0_iter16_reg <= power_center_read_reg_125_pp0_iter15_reg;
        power_center_read_reg_125_pp0_iter17_reg <= power_center_read_reg_125_pp0_iter16_reg;
        power_center_read_reg_125_pp0_iter1_reg <= power_center_read_reg_125;
        power_center_read_reg_125_pp0_iter2_reg <= power_center_read_reg_125_pp0_iter1_reg;
        power_center_read_reg_125_pp0_iter3_reg <= power_center_read_reg_125_pp0_iter2_reg;
        power_center_read_reg_125_pp0_iter4_reg <= power_center_read_reg_125_pp0_iter3_reg;
        power_center_read_reg_125_pp0_iter5_reg <= power_center_read_reg_125_pp0_iter4_reg;
        power_center_read_reg_125_pp0_iter6_reg <= power_center_read_reg_125_pp0_iter5_reg;
        power_center_read_reg_125_pp0_iter7_reg <= power_center_read_reg_125_pp0_iter6_reg;
        power_center_read_reg_125_pp0_iter8_reg <= power_center_read_reg_125_pp0_iter7_reg;
        power_center_read_reg_125_pp0_iter9_reg <= power_center_read_reg_125_pp0_iter8_reg;
        temp_center_read_reg_130 <= temp_center_int_reg;
        temp_center_read_reg_130_pp0_iter10_reg <= temp_center_read_reg_130_pp0_iter9_reg;
        temp_center_read_reg_130_pp0_iter11_reg <= temp_center_read_reg_130_pp0_iter10_reg;
        temp_center_read_reg_130_pp0_iter12_reg <= temp_center_read_reg_130_pp0_iter11_reg;
        temp_center_read_reg_130_pp0_iter13_reg <= temp_center_read_reg_130_pp0_iter12_reg;
        temp_center_read_reg_130_pp0_iter14_reg <= temp_center_read_reg_130_pp0_iter13_reg;
        temp_center_read_reg_130_pp0_iter15_reg <= temp_center_read_reg_130_pp0_iter14_reg;
        temp_center_read_reg_130_pp0_iter16_reg <= temp_center_read_reg_130_pp0_iter15_reg;
        temp_center_read_reg_130_pp0_iter17_reg <= temp_center_read_reg_130_pp0_iter16_reg;
        temp_center_read_reg_130_pp0_iter18_reg <= temp_center_read_reg_130_pp0_iter17_reg;
        temp_center_read_reg_130_pp0_iter19_reg <= temp_center_read_reg_130_pp0_iter18_reg;
        temp_center_read_reg_130_pp0_iter1_reg <= temp_center_read_reg_130;
        temp_center_read_reg_130_pp0_iter20_reg <= temp_center_read_reg_130_pp0_iter19_reg;
        temp_center_read_reg_130_pp0_iter21_reg <= temp_center_read_reg_130_pp0_iter20_reg;
        temp_center_read_reg_130_pp0_iter22_reg <= temp_center_read_reg_130_pp0_iter21_reg;
        temp_center_read_reg_130_pp0_iter23_reg <= temp_center_read_reg_130_pp0_iter22_reg;
        temp_center_read_reg_130_pp0_iter24_reg <= temp_center_read_reg_130_pp0_iter23_reg;
        temp_center_read_reg_130_pp0_iter25_reg <= temp_center_read_reg_130_pp0_iter24_reg;
        temp_center_read_reg_130_pp0_iter26_reg <= temp_center_read_reg_130_pp0_iter25_reg;
        temp_center_read_reg_130_pp0_iter27_reg <= temp_center_read_reg_130_pp0_iter26_reg;
        temp_center_read_reg_130_pp0_iter28_reg <= temp_center_read_reg_130_pp0_iter27_reg;
        temp_center_read_reg_130_pp0_iter29_reg <= temp_center_read_reg_130_pp0_iter28_reg;
        temp_center_read_reg_130_pp0_iter2_reg <= temp_center_read_reg_130_pp0_iter1_reg;
        temp_center_read_reg_130_pp0_iter30_reg <= temp_center_read_reg_130_pp0_iter29_reg;
        temp_center_read_reg_130_pp0_iter31_reg <= temp_center_read_reg_130_pp0_iter30_reg;
        temp_center_read_reg_130_pp0_iter32_reg <= temp_center_read_reg_130_pp0_iter31_reg;
        temp_center_read_reg_130_pp0_iter33_reg <= temp_center_read_reg_130_pp0_iter32_reg;
        temp_center_read_reg_130_pp0_iter34_reg <= temp_center_read_reg_130_pp0_iter33_reg;
        temp_center_read_reg_130_pp0_iter35_reg <= temp_center_read_reg_130_pp0_iter34_reg;
        temp_center_read_reg_130_pp0_iter36_reg <= temp_center_read_reg_130_pp0_iter35_reg;
        temp_center_read_reg_130_pp0_iter37_reg <= temp_center_read_reg_130_pp0_iter36_reg;
        temp_center_read_reg_130_pp0_iter38_reg <= temp_center_read_reg_130_pp0_iter37_reg;
        temp_center_read_reg_130_pp0_iter39_reg <= temp_center_read_reg_130_pp0_iter38_reg;
        temp_center_read_reg_130_pp0_iter3_reg <= temp_center_read_reg_130_pp0_iter2_reg;
        temp_center_read_reg_130_pp0_iter40_reg <= temp_center_read_reg_130_pp0_iter39_reg;
        temp_center_read_reg_130_pp0_iter41_reg <= temp_center_read_reg_130_pp0_iter40_reg;
        temp_center_read_reg_130_pp0_iter42_reg <= temp_center_read_reg_130_pp0_iter41_reg;
        temp_center_read_reg_130_pp0_iter4_reg <= temp_center_read_reg_130_pp0_iter3_reg;
        temp_center_read_reg_130_pp0_iter5_reg <= temp_center_read_reg_130_pp0_iter4_reg;
        temp_center_read_reg_130_pp0_iter6_reg <= temp_center_read_reg_130_pp0_iter5_reg;
        temp_center_read_reg_130_pp0_iter7_reg <= temp_center_read_reg_130_pp0_iter6_reg;
        temp_center_read_reg_130_pp0_iter8_reg <= temp_center_read_reg_130_pp0_iter7_reg;
        temp_center_read_reg_130_pp0_iter9_reg <= temp_center_read_reg_130_pp0_iter8_reg;
        tmp0_reg_174 <= grp_fu_76_p2;
        tmp1_reg_179 <= grp_fu_80_p2;
        tmp1_reg_179_pp0_iter14_reg <= tmp1_reg_179;
        tmp1_reg_179_pp0_iter15_reg <= tmp1_reg_179_pp0_iter14_reg;
        tmp1_reg_179_pp0_iter16_reg <= tmp1_reg_179_pp0_iter15_reg;
        tmp1_reg_179_pp0_iter17_reg <= tmp1_reg_179_pp0_iter16_reg;
        tmp1_reg_179_pp0_iter18_reg <= tmp1_reg_179_pp0_iter17_reg;
        tmp1_reg_179_pp0_iter19_reg <= tmp1_reg_179_pp0_iter18_reg;
        tmp1_reg_179_pp0_iter20_reg <= tmp1_reg_179_pp0_iter19_reg;
        tmp2_reg_199 <= grp_fu_88_p2;
        tmp_reg_158 <= grp_fu_58_p2;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter36 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage0_iter37 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter38 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage0_iter39 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter40 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage0_iter41 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage0_iter42 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage0_iter43 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter44 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage0_iter45 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage0_iter46 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage0_iter47 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage0_iter48 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage0_iter49 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_return = grp_fu_101_p2;

endmodule //workload_hotspot_stencil_core
