// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module workload_buffer_store_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_result1_AWVALID,
        m_axi_result1_AWREADY,
        m_axi_result1_AWADDR,
        m_axi_result1_AWID,
        m_axi_result1_AWLEN,
        m_axi_result1_AWSIZE,
        m_axi_result1_AWBURST,
        m_axi_result1_AWLOCK,
        m_axi_result1_AWCACHE,
        m_axi_result1_AWPROT,
        m_axi_result1_AWQOS,
        m_axi_result1_AWREGION,
        m_axi_result1_AWUSER,
        m_axi_result1_WVALID,
        m_axi_result1_WREADY,
        m_axi_result1_WDATA,
        m_axi_result1_WSTRB,
        m_axi_result1_WLAST,
        m_axi_result1_WID,
        m_axi_result1_WUSER,
        m_axi_result1_ARVALID,
        m_axi_result1_ARREADY,
        m_axi_result1_ARADDR,
        m_axi_result1_ARID,
        m_axi_result1_ARLEN,
        m_axi_result1_ARSIZE,
        m_axi_result1_ARBURST,
        m_axi_result1_ARLOCK,
        m_axi_result1_ARCACHE,
        m_axi_result1_ARPROT,
        m_axi_result1_ARQOS,
        m_axi_result1_ARREGION,
        m_axi_result1_ARUSER,
        m_axi_result1_RVALID,
        m_axi_result1_RREADY,
        m_axi_result1_RDATA,
        m_axi_result1_RLAST,
        m_axi_result1_RID,
        m_axi_result1_RUSER,
        m_axi_result1_RRESP,
        m_axi_result1_BVALID,
        m_axi_result1_BREADY,
        m_axi_result1_BRESP,
        m_axi_result1_BID,
        m_axi_result1_BUSER,
        flag,
        k,
        result_dest,
        result_src_0_address0,
        result_src_0_ce0,
        result_src_0_q0,
        result_src_1_address0,
        result_src_1_ce0,
        result_src_1_q0,
        result_src_2_address0,
        result_src_2_ce0,
        result_src_2_q0,
        result_src_3_address0,
        result_src_3_ce0,
        result_src_3_q0,
        result_src_4_address0,
        result_src_4_ce0,
        result_src_4_q0,
        result_src_5_address0,
        result_src_5_ce0,
        result_src_5_q0,
        result_src_6_address0,
        result_src_6_ce0,
        result_src_6_q0,
        result_src_7_address0,
        result_src_7_ce0,
        result_src_7_q0,
        result_src_8_address0,
        result_src_8_ce0,
        result_src_8_q0,
        result_src_9_address0,
        result_src_9_ce0,
        result_src_9_q0,
        result_src_10_address0,
        result_src_10_ce0,
        result_src_10_q0,
        result_src_11_address0,
        result_src_11_ce0,
        result_src_11_q0,
        result_src_12_address0,
        result_src_12_ce0,
        result_src_12_q0,
        result_src_13_address0,
        result_src_13_ce0,
        result_src_13_q0,
        result_src_14_address0,
        result_src_14_ce0,
        result_src_14_q0,
        result_src_15_address0,
        result_src_15_ce0,
        result_src_15_q0
);

parameter    ap_ST_fsm_state1 = 71'd1;
parameter    ap_ST_fsm_state2 = 71'd2;
parameter    ap_ST_fsm_pp0_stage0 = 71'd4;
parameter    ap_ST_fsm_state6 = 71'd8;
parameter    ap_ST_fsm_state7 = 71'd16;
parameter    ap_ST_fsm_state8 = 71'd32;
parameter    ap_ST_fsm_state9 = 71'd64;
parameter    ap_ST_fsm_state10 = 71'd128;
parameter    ap_ST_fsm_state11 = 71'd256;
parameter    ap_ST_fsm_state12 = 71'd512;
parameter    ap_ST_fsm_state13 = 71'd1024;
parameter    ap_ST_fsm_state14 = 71'd2048;
parameter    ap_ST_fsm_state15 = 71'd4096;
parameter    ap_ST_fsm_state16 = 71'd8192;
parameter    ap_ST_fsm_state17 = 71'd16384;
parameter    ap_ST_fsm_state18 = 71'd32768;
parameter    ap_ST_fsm_state19 = 71'd65536;
parameter    ap_ST_fsm_state20 = 71'd131072;
parameter    ap_ST_fsm_state21 = 71'd262144;
parameter    ap_ST_fsm_state22 = 71'd524288;
parameter    ap_ST_fsm_state23 = 71'd1048576;
parameter    ap_ST_fsm_state24 = 71'd2097152;
parameter    ap_ST_fsm_state25 = 71'd4194304;
parameter    ap_ST_fsm_state26 = 71'd8388608;
parameter    ap_ST_fsm_state27 = 71'd16777216;
parameter    ap_ST_fsm_state28 = 71'd33554432;
parameter    ap_ST_fsm_state29 = 71'd67108864;
parameter    ap_ST_fsm_state30 = 71'd134217728;
parameter    ap_ST_fsm_state31 = 71'd268435456;
parameter    ap_ST_fsm_state32 = 71'd536870912;
parameter    ap_ST_fsm_state33 = 71'd1073741824;
parameter    ap_ST_fsm_state34 = 71'd2147483648;
parameter    ap_ST_fsm_state35 = 71'd4294967296;
parameter    ap_ST_fsm_state36 = 71'd8589934592;
parameter    ap_ST_fsm_state37 = 71'd17179869184;
parameter    ap_ST_fsm_state38 = 71'd34359738368;
parameter    ap_ST_fsm_state39 = 71'd68719476736;
parameter    ap_ST_fsm_state40 = 71'd137438953472;
parameter    ap_ST_fsm_state41 = 71'd274877906944;
parameter    ap_ST_fsm_state42 = 71'd549755813888;
parameter    ap_ST_fsm_state43 = 71'd1099511627776;
parameter    ap_ST_fsm_state44 = 71'd2199023255552;
parameter    ap_ST_fsm_state45 = 71'd4398046511104;
parameter    ap_ST_fsm_state46 = 71'd8796093022208;
parameter    ap_ST_fsm_state47 = 71'd17592186044416;
parameter    ap_ST_fsm_state48 = 71'd35184372088832;
parameter    ap_ST_fsm_state49 = 71'd70368744177664;
parameter    ap_ST_fsm_state50 = 71'd140737488355328;
parameter    ap_ST_fsm_state51 = 71'd281474976710656;
parameter    ap_ST_fsm_state52 = 71'd562949953421312;
parameter    ap_ST_fsm_state53 = 71'd1125899906842624;
parameter    ap_ST_fsm_state54 = 71'd2251799813685248;
parameter    ap_ST_fsm_state55 = 71'd4503599627370496;
parameter    ap_ST_fsm_state56 = 71'd9007199254740992;
parameter    ap_ST_fsm_state57 = 71'd18014398509481984;
parameter    ap_ST_fsm_state58 = 71'd36028797018963968;
parameter    ap_ST_fsm_state59 = 71'd72057594037927936;
parameter    ap_ST_fsm_state60 = 71'd144115188075855872;
parameter    ap_ST_fsm_state61 = 71'd288230376151711744;
parameter    ap_ST_fsm_state62 = 71'd576460752303423488;
parameter    ap_ST_fsm_state63 = 71'd1152921504606846976;
parameter    ap_ST_fsm_state64 = 71'd2305843009213693952;
parameter    ap_ST_fsm_state65 = 71'd4611686018427387904;
parameter    ap_ST_fsm_state66 = 71'd9223372036854775808;
parameter    ap_ST_fsm_state67 = 71'd18446744073709551616;
parameter    ap_ST_fsm_state68 = 71'd36893488147419103232;
parameter    ap_ST_fsm_state69 = 71'd73786976294838206464;
parameter    ap_ST_fsm_state70 = 71'd147573952589676412928;
parameter    ap_ST_fsm_state71 = 71'd295147905179352825856;
parameter    ap_ST_fsm_state72 = 71'd590295810358705651712;
parameter    ap_ST_fsm_state73 = 71'd1180591620717411303424;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_result1_AWVALID;
input   m_axi_result1_AWREADY;
output  [63:0] m_axi_result1_AWADDR;
output  [0:0] m_axi_result1_AWID;
output  [31:0] m_axi_result1_AWLEN;
output  [2:0] m_axi_result1_AWSIZE;
output  [1:0] m_axi_result1_AWBURST;
output  [1:0] m_axi_result1_AWLOCK;
output  [3:0] m_axi_result1_AWCACHE;
output  [2:0] m_axi_result1_AWPROT;
output  [3:0] m_axi_result1_AWQOS;
output  [3:0] m_axi_result1_AWREGION;
output  [0:0] m_axi_result1_AWUSER;
output   m_axi_result1_WVALID;
input   m_axi_result1_WREADY;
output  [511:0] m_axi_result1_WDATA;
output  [63:0] m_axi_result1_WSTRB;
output   m_axi_result1_WLAST;
output  [0:0] m_axi_result1_WID;
output  [0:0] m_axi_result1_WUSER;
output   m_axi_result1_ARVALID;
input   m_axi_result1_ARREADY;
output  [63:0] m_axi_result1_ARADDR;
output  [0:0] m_axi_result1_ARID;
output  [31:0] m_axi_result1_ARLEN;
output  [2:0] m_axi_result1_ARSIZE;
output  [1:0] m_axi_result1_ARBURST;
output  [1:0] m_axi_result1_ARLOCK;
output  [3:0] m_axi_result1_ARCACHE;
output  [2:0] m_axi_result1_ARPROT;
output  [3:0] m_axi_result1_ARQOS;
output  [3:0] m_axi_result1_ARREGION;
output  [0:0] m_axi_result1_ARUSER;
input   m_axi_result1_RVALID;
output   m_axi_result1_RREADY;
input  [511:0] m_axi_result1_RDATA;
input   m_axi_result1_RLAST;
input  [0:0] m_axi_result1_RID;
input  [0:0] m_axi_result1_RUSER;
input  [1:0] m_axi_result1_RRESP;
input   m_axi_result1_BVALID;
output   m_axi_result1_BREADY;
input  [1:0] m_axi_result1_BRESP;
input  [0:0] m_axi_result1_BID;
input  [0:0] m_axi_result1_BUSER;
input  [0:0] flag;
input  [3:0] k;
input  [63:0] result_dest;
output  [10:0] result_src_0_address0;
output   result_src_0_ce0;
input  [31:0] result_src_0_q0;
output  [10:0] result_src_1_address0;
output   result_src_1_ce0;
input  [31:0] result_src_1_q0;
output  [10:0] result_src_2_address0;
output   result_src_2_ce0;
input  [31:0] result_src_2_q0;
output  [10:0] result_src_3_address0;
output   result_src_3_ce0;
input  [31:0] result_src_3_q0;
output  [10:0] result_src_4_address0;
output   result_src_4_ce0;
input  [31:0] result_src_4_q0;
output  [10:0] result_src_5_address0;
output   result_src_5_ce0;
input  [31:0] result_src_5_q0;
output  [10:0] result_src_6_address0;
output   result_src_6_ce0;
input  [31:0] result_src_6_q0;
output  [10:0] result_src_7_address0;
output   result_src_7_ce0;
input  [31:0] result_src_7_q0;
output  [10:0] result_src_8_address0;
output   result_src_8_ce0;
input  [31:0] result_src_8_q0;
output  [10:0] result_src_9_address0;
output   result_src_9_ce0;
input  [31:0] result_src_9_q0;
output  [10:0] result_src_10_address0;
output   result_src_10_ce0;
input  [31:0] result_src_10_q0;
output  [10:0] result_src_11_address0;
output   result_src_11_ce0;
input  [31:0] result_src_11_q0;
output  [10:0] result_src_12_address0;
output   result_src_12_ce0;
input  [31:0] result_src_12_q0;
output  [10:0] result_src_13_address0;
output   result_src_13_ce0;
input  [31:0] result_src_13_q0;
output  [10:0] result_src_14_address0;
output   result_src_14_ce0;
input  [31:0] result_src_14_q0;
output  [10:0] result_src_15_address0;
output   result_src_15_ce0;
input  [31:0] result_src_15_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_result1_AWVALID;
reg m_axi_result1_WVALID;
reg m_axi_result1_BREADY;
reg result_src_0_ce0;
reg result_src_1_ce0;
reg result_src_2_ce0;
reg result_src_3_ce0;
reg result_src_4_ce0;
reg result_src_5_ce0;
reg result_src_6_ce0;
reg result_src_7_ce0;
reg result_src_8_ce0;
reg result_src_9_ce0;
reg result_src_10_ce0;
reg result_src_11_ce0;
reg result_src_12_ce0;
reg result_src_13_ce0;
reg result_src_14_ce0;
reg result_src_15_ce0;

(* fsm_encoding = "none" *) reg   [70:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    result1_blk_n_AW;
wire    ap_CS_fsm_state2;
reg    result1_blk_n_W;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln2095_reg_525;
reg   [0:0] icmp_ln2095_reg_525_pp0_iter1_reg;
reg    result1_blk_n_B;
wire    ap_CS_fsm_state73;
wire   [0:0] flag_read_read_fu_114_p2;
reg   [11:0] i_reg_344;
reg   [57:0] trunc_ln_reg_514;
wire   [0:0] icmp_ln2095_fu_393_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_state5_io;
reg    ap_block_pp0_stage0_11001;
wire   [11:0] i_3_fu_399_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [31:0] result_src_0_load_reg_614;
reg   [31:0] result_src_1_load_reg_619;
reg   [31:0] result_src_2_load_reg_624;
reg   [31:0] result_src_3_load_reg_629;
reg   [31:0] result_src_4_load_reg_634;
reg   [31:0] result_src_5_load_reg_639;
reg   [31:0] result_src_6_load_reg_644;
reg   [31:0] result_src_7_load_reg_649;
reg   [31:0] result_src_8_load_reg_654;
reg   [31:0] result_src_9_load_reg_659;
reg   [31:0] result_src_10_load_reg_664;
reg   [31:0] result_src_11_load_reg_669;
reg   [31:0] result_src_12_load_reg_674;
reg   [31:0] result_src_13_load_reg_679;
reg   [31:0] result_src_14_load_reg_684;
reg   [31:0] result_src_15_load_reg_689;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
wire   [63:0] zext_ln2095_fu_405_p1;
wire  signed [63:0] sext_ln2095_fu_383_p1;
reg    ap_block_state73;
wire    ap_block_pp0_stage0_01001;
wire   [20:0] tmp_fu_355_p3;
wire  signed [63:0] p_cast_fu_363_p1;
wire   [63:0] empty_fu_367_p2;
wire   [31:0] bitcast_ln2101_15_fu_470_p1;
wire   [31:0] bitcast_ln2101_14_fu_467_p1;
wire   [31:0] bitcast_ln2101_13_fu_464_p1;
wire   [31:0] bitcast_ln2101_12_fu_461_p1;
wire   [31:0] bitcast_ln2101_11_fu_458_p1;
wire   [31:0] bitcast_ln2101_10_fu_455_p1;
wire   [31:0] bitcast_ln2101_9_fu_452_p1;
wire   [31:0] bitcast_ln2101_8_fu_449_p1;
wire   [31:0] bitcast_ln2101_7_fu_446_p1;
wire   [31:0] bitcast_ln2101_6_fu_443_p1;
wire   [31:0] bitcast_ln2101_5_fu_440_p1;
wire   [31:0] bitcast_ln2101_4_fu_437_p1;
wire   [31:0] bitcast_ln2101_3_fu_434_p1;
wire   [31:0] bitcast_ln2101_2_fu_431_p1;
wire   [31:0] bitcast_ln2101_1_fu_428_p1;
wire   [31:0] bitcast_ln2101_fu_425_p1;
reg   [70:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 71'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((m_axi_result1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((m_axi_result1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln2095_fu_393_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_344 <= i_3_fu_399_p2;
    end else if (((m_axi_result1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_344 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln2095_reg_525 <= icmp_ln2095_fu_393_p2;
        icmp_ln2095_reg_525_pp0_iter1_reg <= icmp_ln2095_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2095_reg_525 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_0_load_reg_614 <= result_src_0_q0;
        result_src_10_load_reg_664 <= result_src_10_q0;
        result_src_11_load_reg_669 <= result_src_11_q0;
        result_src_12_load_reg_674 <= result_src_12_q0;
        result_src_13_load_reg_679 <= result_src_13_q0;
        result_src_14_load_reg_684 <= result_src_14_q0;
        result_src_15_load_reg_689 <= result_src_15_q0;
        result_src_1_load_reg_619 <= result_src_1_q0;
        result_src_2_load_reg_624 <= result_src_2_q0;
        result_src_3_load_reg_629 <= result_src_3_q0;
        result_src_4_load_reg_634 <= result_src_4_q0;
        result_src_5_load_reg_639 <= result_src_5_q0;
        result_src_6_load_reg_644 <= result_src_6_q0;
        result_src_7_load_reg_649 <= result_src_7_q0;
        result_src_8_load_reg_654 <= result_src_8_q0;
        result_src_9_load_reg_659 <= result_src_9_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (flag == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        trunc_ln_reg_514 <= {{empty_fu_367_p2[63:6]}};
    end
end

always @ (*) begin
    if ((icmp_ln2095_fu_393_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | (~((flag == 1'd1) & (m_axi_result1_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state73)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((flag == 1'd1) & (m_axi_result1_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state73))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_result1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_result1_AWVALID = 1'b1;
    end else begin
        m_axi_result1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((flag == 1'd1) & (m_axi_result1_BVALID == 1'b0)) & (flag == 1'd1) & (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_result1_BREADY = 1'b1;
    end else begin
        m_axi_result1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2095_reg_525_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_result1_WVALID = 1'b1;
    end else begin
        m_axi_result1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        result1_blk_n_AW = m_axi_result1_AWREADY;
    end else begin
        result1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((flag == 1'd1) & (1'b1 == ap_CS_fsm_state73))) begin
        result1_blk_n_B = m_axi_result1_BVALID;
    end else begin
        result1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln2095_reg_525_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        result1_blk_n_W = m_axi_result1_WREADY;
    end else begin
        result1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_0_ce0 = 1'b1;
    end else begin
        result_src_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_10_ce0 = 1'b1;
    end else begin
        result_src_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_11_ce0 = 1'b1;
    end else begin
        result_src_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_12_ce0 = 1'b1;
    end else begin
        result_src_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_13_ce0 = 1'b1;
    end else begin
        result_src_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_14_ce0 = 1'b1;
    end else begin
        result_src_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_15_ce0 = 1'b1;
    end else begin
        result_src_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_1_ce0 = 1'b1;
    end else begin
        result_src_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_2_ce0 = 1'b1;
    end else begin
        result_src_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_3_ce0 = 1'b1;
    end else begin
        result_src_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_4_ce0 = 1'b1;
    end else begin
        result_src_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_5_ce0 = 1'b1;
    end else begin
        result_src_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_6_ce0 = 1'b1;
    end else begin
        result_src_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_7_ce0 = 1'b1;
    end else begin
        result_src_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_8_ce0 = 1'b1;
    end else begin
        result_src_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_src_9_ce0 = 1'b1;
    end else begin
        result_src_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (flag_read_read_fu_114_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end else if (((ap_start == 1'b1) & (flag == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((m_axi_result1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln2095_fu_393_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln2095_fu_393_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            if ((~((flag == 1'd1) & (m_axi_result1_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state73))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd70];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b1 == ap_block_state5_io) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b1 == ap_block_state5_io) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((icmp_ln2095_reg_525_pp0_iter1_reg == 1'd0) & (m_axi_result1_WREADY == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state73 = ((flag == 1'd1) & (m_axi_result1_BVALID == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign bitcast_ln2101_10_fu_455_p1 = result_src_10_load_reg_664;

assign bitcast_ln2101_11_fu_458_p1 = result_src_11_load_reg_669;

assign bitcast_ln2101_12_fu_461_p1 = result_src_12_load_reg_674;

assign bitcast_ln2101_13_fu_464_p1 = result_src_13_load_reg_679;

assign bitcast_ln2101_14_fu_467_p1 = result_src_14_load_reg_684;

assign bitcast_ln2101_15_fu_470_p1 = result_src_15_load_reg_689;

assign bitcast_ln2101_1_fu_428_p1 = result_src_1_load_reg_619;

assign bitcast_ln2101_2_fu_431_p1 = result_src_2_load_reg_624;

assign bitcast_ln2101_3_fu_434_p1 = result_src_3_load_reg_629;

assign bitcast_ln2101_4_fu_437_p1 = result_src_4_load_reg_634;

assign bitcast_ln2101_5_fu_440_p1 = result_src_5_load_reg_639;

assign bitcast_ln2101_6_fu_443_p1 = result_src_6_load_reg_644;

assign bitcast_ln2101_7_fu_446_p1 = result_src_7_load_reg_649;

assign bitcast_ln2101_8_fu_449_p1 = result_src_8_load_reg_654;

assign bitcast_ln2101_9_fu_452_p1 = result_src_9_load_reg_659;

assign bitcast_ln2101_fu_425_p1 = result_src_0_load_reg_614;

assign empty_fu_367_p2 = ($signed(p_cast_fu_363_p1) + $signed(result_dest));

assign flag_read_read_fu_114_p2 = flag;

assign i_3_fu_399_p2 = (i_reg_344 + 12'd1);

assign icmp_ln2095_fu_393_p2 = ((i_reg_344 == 12'd2048) ? 1'b1 : 1'b0);

assign m_axi_result1_ARADDR = 64'd0;

assign m_axi_result1_ARBURST = 2'd0;

assign m_axi_result1_ARCACHE = 4'd0;

assign m_axi_result1_ARID = 1'd0;

assign m_axi_result1_ARLEN = 32'd0;

assign m_axi_result1_ARLOCK = 2'd0;

assign m_axi_result1_ARPROT = 3'd0;

assign m_axi_result1_ARQOS = 4'd0;

assign m_axi_result1_ARREGION = 4'd0;

assign m_axi_result1_ARSIZE = 3'd0;

assign m_axi_result1_ARUSER = 1'd0;

assign m_axi_result1_ARVALID = 1'b0;

assign m_axi_result1_AWADDR = sext_ln2095_fu_383_p1;

assign m_axi_result1_AWBURST = 2'd0;

assign m_axi_result1_AWCACHE = 4'd0;

assign m_axi_result1_AWID = 1'd0;

assign m_axi_result1_AWLEN = 32'd2048;

assign m_axi_result1_AWLOCK = 2'd0;

assign m_axi_result1_AWPROT = 3'd0;

assign m_axi_result1_AWQOS = 4'd0;

assign m_axi_result1_AWREGION = 4'd0;

assign m_axi_result1_AWSIZE = 3'd0;

assign m_axi_result1_AWUSER = 1'd0;

assign m_axi_result1_RREADY = 1'b0;

assign m_axi_result1_WDATA = {{{{{{{{{{{{{{{{bitcast_ln2101_15_fu_470_p1}, {bitcast_ln2101_14_fu_467_p1}}, {bitcast_ln2101_13_fu_464_p1}}, {bitcast_ln2101_12_fu_461_p1}}, {bitcast_ln2101_11_fu_458_p1}}, {bitcast_ln2101_10_fu_455_p1}}, {bitcast_ln2101_9_fu_452_p1}}, {bitcast_ln2101_8_fu_449_p1}}, {bitcast_ln2101_7_fu_446_p1}}, {bitcast_ln2101_6_fu_443_p1}}, {bitcast_ln2101_5_fu_440_p1}}, {bitcast_ln2101_4_fu_437_p1}}, {bitcast_ln2101_3_fu_434_p1}}, {bitcast_ln2101_2_fu_431_p1}}, {bitcast_ln2101_1_fu_428_p1}}, {bitcast_ln2101_fu_425_p1}};

assign m_axi_result1_WID = 1'd0;

assign m_axi_result1_WLAST = 1'b0;

assign m_axi_result1_WSTRB = 64'd18446744073709551615;

assign m_axi_result1_WUSER = 1'd0;

assign p_cast_fu_363_p1 = $signed(tmp_fu_355_p3);

assign result_src_0_address0 = zext_ln2095_fu_405_p1;

assign result_src_10_address0 = zext_ln2095_fu_405_p1;

assign result_src_11_address0 = zext_ln2095_fu_405_p1;

assign result_src_12_address0 = zext_ln2095_fu_405_p1;

assign result_src_13_address0 = zext_ln2095_fu_405_p1;

assign result_src_14_address0 = zext_ln2095_fu_405_p1;

assign result_src_15_address0 = zext_ln2095_fu_405_p1;

assign result_src_1_address0 = zext_ln2095_fu_405_p1;

assign result_src_2_address0 = zext_ln2095_fu_405_p1;

assign result_src_3_address0 = zext_ln2095_fu_405_p1;

assign result_src_4_address0 = zext_ln2095_fu_405_p1;

assign result_src_5_address0 = zext_ln2095_fu_405_p1;

assign result_src_6_address0 = zext_ln2095_fu_405_p1;

assign result_src_7_address0 = zext_ln2095_fu_405_p1;

assign result_src_8_address0 = zext_ln2095_fu_405_p1;

assign result_src_9_address0 = zext_ln2095_fu_405_p1;

assign sext_ln2095_fu_383_p1 = $signed(trunc_ln_reg_514);

assign tmp_fu_355_p3 = {{k}, {17'd0}};

assign zext_ln2095_fu_405_p1 = i_reg_344;

endmodule //workload_buffer_store_1
